language: php

php:
  - 5.4
  - 5.5
  - 5.6

install: composer install

script:
  - php vender/bin/phpunit
  - php vender/bin/phpcs --standard=PSR2 src/
  - find src/ -type f -name *.php -exec php -l {} \; | grep "Errors parsing ";
